### ISSUE TITLE
Team.Info Structure Changed

### ISSUE THREAD

**Issue by ApexAutomation** [peakey-com/slack-library-.net#1]
It appears the Team.Info item structure has changed. Even though https://api.slack.com/methods/team.info shows Icon structure correct, running the tester will reveal a different response (no image_default). Fix or comment out line 133 of the MetaData.cs class will allow a connection.

**Comment by randall-peakey-com** [comment]
I was unable to reproduce this issue.  I have, however, updated the line to default to true if the slack message does not include image_default.

Can you verify that this solves the issue?

**Comment by ApexAutomation** [comment]
Please accept my apologies for the late response...Yes this fixed my issue, thank you.
