### ISSUE TITLE
Dependency on Websockets, Win8 or newer

### ISSUE THREAD

**Issue by hamsando** [peakey-com/slack-library-.net#2]
The DLL and Test app compile and run just fine, in the sense that they don't crash. However while on Win10 (and I presume Win8 and Win8.1) the connection to Slack is immediate and successful, on Win7 the connection does not work. The retry mechanism of the Test app kicks in and it does retry, however it always fails. 

My guess is that the DLL is reliant on the MS Websockets implementation, which, as per Microsoft ..

"The class elements in the System.Net.WebSockets namespace that are supported on Windows 7, Windows Vista SP2, and Windows Server 2008 are abstract class elements."

May suggest either switching to something like websocket-sharp or adding a note in the Readme identifying this limitation.

**Comment by randall-peakey-com** [comment]
You are correct, the slack connection uses WebSockets and will require a minimum of Windows 8.
I've updated the readme to make note of this limitation.

**Comment by hamsando** [comment]
Thanks for that - it wasn't really a bug, but I appreciate the added note in the Readme so that some other soul on Win7 doesn't end up getting irritated as to why it doesn't work.
